pipeline {
    agent { label 'terraform-agent'}

    environment {
        AWS_REGION = 'eu-west-1'
    }

    stages {

        stage("Checkout") {
            steps {
                // Checkout source code from git
                git branch: 'master', url: 'https://github.com/chris-zano/terraform.git'
            }
        }

        stage('Install Terraform') {
            steps {
                script {
                    // Ensure Terraform is installed in the environment
                    sh '''
                    wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
                    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
                    sudo apt update && sudo apt install terraform
                    '''
                }
            }
        }

        stage('Terraform Init') {
            steps {
                script {
                    // Initialize Terraform with backend configuration
                    sh '''
                    terraform init
                    '''
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                script {
                    // Generate and show an execution plan
                    sh '''
                    terraform plan
                    '''
                }
            }
        }
        
        stage('Terraform Validate') {
            steps {
                script {
                    // Generate and show an execution plan
                    sh '''
                    terraform validate
                    '''
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                script {
                    // Apply the plan to provision resources
                    sh '''
                    terraform apply -auto-approve
                    '''
                }
            }
        }

        stage('Terraform Output') {
            steps {
                script {
                    // Fetch the outputs from Terraform
                    sh '''
                    terraform output
                    '''
                }
            }
        }
    }

    post {
        always {
            // Clean workspace
            cleanWs()
        }
    }
}
