pipeline {
    agent { label 'terraform'}

    stages {

        stage("Checkout") {
            steps {
                // Checkout source code from git
                git branch: 'master', url: 'https://github.com/chris-zano/terraform.git'
            }
        }

        stage("Run Terraform init with cli arguments") {
            steps {
                withCredentials([file(credentialsId: 'tfbackend', variable: 'tfbackend')]) {
                    sh "cp $tfbackend terraform.tfbackend && chmod 600 terraform.tfbackend"
                    sh '''
                    terraform init -backend-config="terraform.tfbackend"
                    '''
                } 
            }
        }

        stage('Terraform Plan') {
            steps {
                withCredentials([file(credentialsId: 'tfvars', variable: 'tfvars')]) {
                    sh '''
                    cp $tfvars terraform.tfvars && chmod 600 terraform.tfvars
                    terraform plan -var-file=terraform.tfvars -out=terraform.tfplan
                    '''
                }        
            }
        }
        
        stage('Terraform Validate') {
            steps {
                script {
                    // Generate and show an execution plan
                    sh '''
                    terraform validate
                    '''
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                script {
                    // Apply the plan to provision resources
                    withCredentials([file(credentialsId: 'tfvars', variable: 'tfvars')]) {
                    sh '''
                    cp $tfvars terraform.tfvars && chmod 600 terraform.tfvars
                    terraform apply terraform.tfplan -auto-approve
                    '''
                }
                }
            }
        }

        stage('Terraform Output') {
            steps {
                script {
                    // Fetch the outputs from Terraform
                    sh '''
                    terraform output
                    '''
                }
            }
        }
    }

    post {
        always {
            // Clean workspace
            deleteDir()
            cleanWs()
        }
    }
}
