pipeline {
    agent { label 'jenkins-agent'}

    environment {
        TF_IN_AUTOMATION = "true"
        AWS_REGION = 'eu-west-1'
    }

    stages {

        stage("Checkout") {
            steps {
                // Checkout source code from git
                git branch: 'main', url: 'https://github.com/chris-zano/terraform.git'
            }
        }

        stage('Install Terraform') {
            steps {
                script {
                    // Ensure Terraform is installed in the environment
                    sh '''
                    curl -sLo terraform.zip https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip
                    unzip terraform.zip
                    sudo mv terraform /usr/local/bin/
                    terraform --version
                    '''
                }
            }
        }

        stage('Terraform Init') {
            steps {
                script {
                    // Initialize Terraform with backend configuration
                    sh '''
                    terraform init
                    '''
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                script {
                    // Generate and show an execution plan
                    sh '''
                    terraform plan
                    '''
                }
            }
        }
        
        stage('Terraform Validate') {
            steps {
                script {
                    // Generate and show an execution plan
                    sh '''
                    terraform validate
                    '''
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                script {
                    // Apply the plan to provision resources
                    sh '''
                    terraform apply -auto-approve
                    '''
                }
            }
        }

        stage('Terraform Output') {
            steps {
                script {
                    // Fetch the outputs from Terraform
                    sh '''
                    terraform output
                    '''
                }
            }
        }
    }

    post {
        always {
            // Clean workspace
            cleanWs()
        }
    }
}
